name: Build and Push

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.REPOSITORY_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Get Repository name
      run: echo USER_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build Docker Image
      run: make build   
    - name: Push Docker Image
      run: make push